server:
  address: localhost
  port: 8090
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-falace
      repositories:
        type: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_ACCOUNT@gmail.com
    password: GMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

auth:
  registration:
    emailVerification: false
  login:
    restrictVerified: false
  secretKey: